"""
WafDetector - Detekcja Web Application Firewall (WAF)
"""

import requests
from typing import Optional, Dict, List


class WafDetector:
    """Detekcja WAF na podstawie sygnatury"""
    
    WAF_SIGNATURES = {
        "Cloudflare": {
            "headers": ["Server: cloudflare", "CF-RAY"],
            "status_codes": [403],
            "body_keywords": ["Cloudflare Ray ID", "DDoS protection by Cloudflare"]
        },
        "Sucuri": {
            "headers": ["Server: Sucuri/Cloudproxy", "X-Sucuri-ID"],
            "status_codes": [403],
            "body_keywords": ["Sucuri WebSite Firewall - Access Denied"]
        },
        "Incapsula": {
            "headers": ["X-CDN: Incapsula"],
            "status_codes": [403],
            "body_keywords": ["Incapsula incident ID"]
        },
        "Akamai": {
            "headers": ["Server: AkamaiGHost"],
            "status_codes": [403],
            "body_keywords": ["You don't have permission to access"]
        },
        "ModSecurity": {
            "headers": ["Server: Mod_Security", "Server: ModSecurity"],
            "status_codes": [403, 406],
            "body_keywords": ["Mod_Security", "ModSecurity"]
        },
        "Wordfence": {
            "headers": [],
            "status_codes": [403],
            "body_keywords": ["Generated by Wordfence"]
        },
        "Generic WAF": {
            "headers": ["X-WAF", "X-WAF-Event"],
            "status_codes": [403, 406, 501, 503],
            "body_keywords": ["Access Denied", "Forbidden", "blocked", "firewall"]
        }
    }
    
    def __init__(self, session: requests.Session):
        """
        Inicjalizacja detektora WAF
        
        Args:
            session: Sesja requests do używania
        """
        self.session = session
    
    def detect_waf(self, url: str, headers: Dict = None, timeout: int = 5, payloads: List[str] = None) -> str:
        """
        Detekcja WAF na stronie
        
        Args:
            url: URL do testowania
            headers: Nagłówki HTTP
            timeout: Timeout żądań
            payloads: Lista payloadów WAF (jeśli None, użyj domyślnych)
        
        Returns:
            Nazwa wykrytego WAF lub "None"
        """
        if payloads is None:
            payloads = [
                "' OR 1=1--",
                "<script>alert(1)</script>",
                "UNION SELECT NULL,NULL,NULL--",
                "SLEEP(5)",
            ]
        
        if headers is None:
            headers = {}
        
        # Pobierz baseline response
        try:
            baseline_response = self.session.get(url, headers=headers, timeout=timeout, verify=False)
        except requests.exceptions.RequestException:
            return "Error (Baseline Request Failed)"
        
        # Testuj payloady WAF
        for payload in payloads:
            test_url = f"{url}?id={payload}"
            try:
                waf_response = self.session.get(test_url, headers=headers, timeout=timeout, verify=False)
                
                # Sprawdź sygnatury
                for waf_name, signatures in self.WAF_SIGNATURES.items():
                    # Sprawdzenie nagłówków
                    for header_sig in signatures.get("headers", []):
                        if header_sig.lower() in str(waf_response.headers).lower():
                            return waf_name
                    
                    # Sprawdzenie kodów statusu
                    if waf_response.status_code in signatures.get("status_codes", []):
                        if waf_response.status_code != baseline_response.status_code:
                            return waf_name
                    
                    # Sprawdzenie słów kluczowych w body
                    for keyword in signatures.get("body_keywords", []):
                        if keyword.lower() in waf_response.text.lower():
                            return waf_name
            
            except requests.exceptions.RequestException:
                continue
        
        return "None"
    
    def detect_tech_from_headers(self, headers: Dict) -> str:
        """
        Rozpoznaje technologię bazy danych na podstawie nagłówków HTTP
        
        Args:
            headers: Nagłówki HTTP odpowiedzi
        
        Returns:
            Typ technologii (MySQL, PostgreSQL, MSSQL, Oracle, SQLite, Generic)
        """
        server = headers.get('Server', '').lower()
        powered = headers.get('X-Powered-By', '').lower()
        combined = f"{server} {powered}"
        
        if any(x in combined for x in ["mysql", "mariadb"]):
            return "MySQL"
        if any(x in combined for x in ["postgresql", "postgres"]):
            return "PostgreSQL"
        if any(x in combined for x in ["microsoft", "iis", "mssql", "sql server"]):
            return "MSSQL"
        if "oracle" in combined:
            return "Oracle"
        if "sqlite" in combined:
            return "SQLite"
        
        return "Generic"
